<?php
/**
 * UserApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
<<<<<<< HEAD
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
=======
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UserApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserApi
{

    /**
     * API Client
<<<<<<< HEAD
     *
     * @var \Swagger\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \Swagger\Client\ApiClient|null $apiClient The api client to use
     */
    function __construct(\Swagger\Client\ApiClient $apiClient = null)
=======
     * @var \Swagger\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \Swagger\Client\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('http://petstore.swagger.io/v2');
        }
<<<<<<< HEAD

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
=======
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return \Swagger\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
<<<<<<< HEAD

    /**
     * Set the API client
     *
     * @param \Swagger\Client\ApiClient $apiClient set the API client
     *
     * @return UserApi
     */
    public function setApiClient(\Swagger\Client\ApiClient $apiClient)
=======
  
    /**
     * Set the API client
     * @param \Swagger\Client\ApiClient $apiClient set the API client
     * @return UserApi
     */
    public function setApiClient(ApiClient $apiClient)
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
    {
        $this->apiClient = $apiClient;
        return $this;
    }
<<<<<<< HEAD

    /**
     * Operation createUser
=======
  
    /**
     * createUser
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     *
     * Create user
     *
     * @param \Swagger\Client\Model\User $body Created user object (optional)
<<<<<<< HEAD
     *
=======
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createUser($body = null)
    {
<<<<<<< HEAD
        list($response) = $this->createUserWithHttpInfo($body);
        return $response;
=======
        list($response) = $this->createUserWithHttpInfo ($body);
        return $response; 
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
    }


    /**
<<<<<<< HEAD
     * Operation createUserWithHttpInfo
=======
     * createUserWithHttpInfo
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     *
     * Create user
     *
     * @param \Swagger\Client\Model\User $body Created user object (optional)
<<<<<<< HEAD
     *
=======
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createUserWithHttpInfo($body = null)
    {
        
<<<<<<< HEAD
=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // parse inputs
        $resourcePath = "/user";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json', 'application/xml'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
            throw $e;
        }
    }
    /**
<<<<<<< HEAD
     * Operation createUsersWithArrayInput
=======
     * createUsersWithArrayInput
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     *
     * Creates list of users with given input array
     *
     * @param \Swagger\Client\Model\User[] $body List of user object (optional)
<<<<<<< HEAD
     *
=======
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createUsersWithArrayInput($body = null)
    {
<<<<<<< HEAD
        list($response) = $this->createUsersWithArrayInputWithHttpInfo($body);
        return $response;
=======
        list($response) = $this->createUsersWithArrayInputWithHttpInfo ($body);
        return $response; 
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
    }


    /**
<<<<<<< HEAD
     * Operation createUsersWithArrayInputWithHttpInfo
=======
     * createUsersWithArrayInputWithHttpInfo
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     *
     * Creates list of users with given input array
     *
     * @param \Swagger\Client\Model\User[] $body List of user object (optional)
<<<<<<< HEAD
     *
=======
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createUsersWithArrayInputWithHttpInfo($body = null)
    {
        
<<<<<<< HEAD
=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // parse inputs
        $resourcePath = "/user/createWithArray";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json', 'application/xml'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
            throw $e;
        }
    }
    /**
<<<<<<< HEAD
     * Operation createUsersWithListInput
=======
     * createUsersWithListInput
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     *
     * Creates list of users with given input array
     *
     * @param \Swagger\Client\Model\User[] $body List of user object (optional)
<<<<<<< HEAD
     *
=======
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createUsersWithListInput($body = null)
    {
<<<<<<< HEAD
        list($response) = $this->createUsersWithListInputWithHttpInfo($body);
        return $response;
=======
        list($response) = $this->createUsersWithListInputWithHttpInfo ($body);
        return $response; 
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
    }


    /**
<<<<<<< HEAD
     * Operation createUsersWithListInputWithHttpInfo
=======
     * createUsersWithListInputWithHttpInfo
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     *
     * Creates list of users with given input array
     *
     * @param \Swagger\Client\Model\User[] $body List of user object (optional)
<<<<<<< HEAD
     *
=======
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createUsersWithListInputWithHttpInfo($body = null)
    {
        
<<<<<<< HEAD
=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // parse inputs
        $resourcePath = "/user/createWithList";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json', 'application/xml'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
            throw $e;
        }
    }
    /**
<<<<<<< HEAD
     * Operation deleteUser
=======
     * deleteUser
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     *
     * Delete user
     *
     * @param string $username The name that needs to be deleted (required)
<<<<<<< HEAD
     *
=======
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function deleteUser($username)
    {
<<<<<<< HEAD
        list($response) = $this->deleteUserWithHttpInfo($username);
        return $response;
=======
        list($response) = $this->deleteUserWithHttpInfo ($username);
        return $response; 
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
    }


    /**
<<<<<<< HEAD
     * Operation deleteUserWithHttpInfo
=======
     * deleteUserWithHttpInfo
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     *
     * Delete user
     *
     * @param string $username The name that needs to be deleted (required)
<<<<<<< HEAD
     *
=======
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function deleteUserWithHttpInfo($username)
    {
        
        // verify the required parameter 'username' is set
        if ($username === null) {
            throw new \InvalidArgumentException('Missing the required parameter $username when calling deleteUser');
        }
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // parse inputs
        $resourcePath = "/user/{username}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json', 'application/xml'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        
        
        // path params
        if ($username !== null) {
            $resourcePath = str_replace(
                "{" . "username" . "}",
                $this->apiClient->getSerializer()->toPathValue($username),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
            throw $e;
        }
    }
    /**
<<<<<<< HEAD
     * Operation getUserByName
=======
     * getUserByName
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     *
     * Get user by user name
     *
     * @param string $username The name that needs to be fetched. Use user1 for testing.  (required)
<<<<<<< HEAD
     *
=======
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return \Swagger\Client\Model\User
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getUserByName($username)
    {
<<<<<<< HEAD
        list($response) = $this->getUserByNameWithHttpInfo($username);
        return $response;
=======
        list($response) = $this->getUserByNameWithHttpInfo ($username);
        return $response; 
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
    }


    /**
<<<<<<< HEAD
     * Operation getUserByNameWithHttpInfo
=======
     * getUserByNameWithHttpInfo
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     *
     * Get user by user name
     *
     * @param string $username The name that needs to be fetched. Use user1 for testing.  (required)
<<<<<<< HEAD
     *
=======
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return Array of \Swagger\Client\Model\User, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getUserByNameWithHttpInfo($username)
    {
        
        // verify the required parameter 'username' is set
        if ($username === null) {
            throw new \InvalidArgumentException('Missing the required parameter $username when calling getUserByName');
        }
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // parse inputs
        $resourcePath = "/user/{username}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json', 'application/xml'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        
        
        // path params
        if ($username !== null) {
            $resourcePath = str_replace(
                "{" . "username" . "}",
                $this->apiClient->getSerializer()->toPathValue($username),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\User'
            );
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\User', $httpHeader), $statusCode, $httpHeader);
                    } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\User', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
            throw $e;
        }
    }
    /**
<<<<<<< HEAD
     * Operation loginUser
=======
     * loginUser
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     *
     * Logs user into the system
     *
     * @param string $username The user name for login (optional)
     * @param string $password The password for login in clear text (optional)
<<<<<<< HEAD
     *
=======
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return string
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function loginUser($username = null, $password = null)
    {
<<<<<<< HEAD
        list($response) = $this->loginUserWithHttpInfo($username, $password);
        return $response;
=======
        list($response) = $this->loginUserWithHttpInfo ($username, $password);
        return $response; 
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
    }


    /**
<<<<<<< HEAD
     * Operation loginUserWithHttpInfo
=======
     * loginUserWithHttpInfo
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     *
     * Logs user into the system
     *
     * @param string $username The user name for login (optional)
     * @param string $password The password for login in clear text (optional)
<<<<<<< HEAD
     *
=======
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return Array of string, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function loginUserWithHttpInfo($username = null, $password = null)
    {
        
<<<<<<< HEAD
=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // parse inputs
        $resourcePath = "/user/login";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json', 'application/xml'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // query params
        if ($username !== null) {
            $queryParams['username'] = $this->apiClient->getSerializer()->toQueryValue($username);
        }// query params
        if ($password !== null) {
            $queryParams['password'] = $this->apiClient->getSerializer()->toQueryValue($password);
        }
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams, 'string'
            );
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array($this->apiClient->getSerializer()->deserialize($response, 'string', $httpHeader), $statusCode, $httpHeader);
                    } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
            throw $e;
        }
    }
    /**
<<<<<<< HEAD
     * Operation logoutUser
     *
     * Logs out current logged in user session
     *
     *
=======
     * logoutUser
     *
     * Logs out current logged in user session
     *
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function logoutUser()
    {
<<<<<<< HEAD
        list($response) = $this->logoutUserWithHttpInfo();
        return $response;
=======
        list($response) = $this->logoutUserWithHttpInfo ();
        return $response; 
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
    }


    /**
<<<<<<< HEAD
     * Operation logoutUserWithHttpInfo
     *
     * Logs out current logged in user session
     *
     *
=======
     * logoutUserWithHttpInfo
     *
     * Logs out current logged in user session
     *
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function logoutUserWithHttpInfo()
    {
        
<<<<<<< HEAD
=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // parse inputs
        $resourcePath = "/user/logout";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json', 'application/xml'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'GET',
                $queryParams, $httpBody,
                $headerParams
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
            throw $e;
        }
    }
    /**
<<<<<<< HEAD
     * Operation updateUser
=======
     * updateUser
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     *
     * Updated user
     *
     * @param string $username name that need to be deleted (required)
     * @param \Swagger\Client\Model\User $body Updated user object (optional)
<<<<<<< HEAD
     *
=======
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return void
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function updateUser($username, $body = null)
    {
<<<<<<< HEAD
        list($response) = $this->updateUserWithHttpInfo($username, $body);
        return $response;
=======
        list($response) = $this->updateUserWithHttpInfo ($username, $body);
        return $response; 
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
    }


    /**
<<<<<<< HEAD
     * Operation updateUserWithHttpInfo
=======
     * updateUserWithHttpInfo
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     *
     * Updated user
     *
     * @param string $username name that need to be deleted (required)
     * @param \Swagger\Client\Model\User $body Updated user object (optional)
<<<<<<< HEAD
     *
=======
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
     * @return Array of null, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function updateUserWithHttpInfo($username, $body = null)
    {
        
        // verify the required parameter 'username' is set
        if ($username === null) {
            throw new \InvalidArgumentException('Missing the required parameter $username when calling updateUser');
        }
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // parse inputs
        $resourcePath = "/user/{username}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = $this->apiClient->selectHeaderAccept(array('application/json', 'application/xml'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(array());
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        
        
        // path params
        if ($username !== null) {
            $resourcePath = str_replace(
                "{" . "username" . "}",
                $this->apiClient->getSerializer()->toPathValue($username),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
                // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams
            );

            return array(null, $statusCode, $httpHeader);
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            }
<<<<<<< HEAD

=======
  
>>>>>>> aeceb658d4ba69e49d60a9d57c324b11c1d4cd9b
            throw $e;
        }
    }
}
