<?php
/**
 * PetApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
<<<<<<< HEAD
 * Please update the test case below to test the endpoint.
=======
 * Do not edit the class manually.
>>>>>>> 43c0c359d3be3bcd7168b43937abd3341cc4207f
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PetApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PetApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
<<<<<<< HEAD
     * Test case for addPet
     *
     * Add a new pet to the store
     *
     */
    public function test_addPet() {

    }
    
    /**
     * Test case for addPetUsingByteArray
     *
     * Fake endpoint to test byte array in body parameter for adding a new pet to the store
     *
     */
    public function test_addPetUsingByteArray() {
=======
     * Test case for updatePet
     *
     * Update an existing pet
     *
     */
    public function test_updatePet() {
>>>>>>> 43c0c359d3be3bcd7168b43937abd3341cc4207f

    }
    
    /**
<<<<<<< HEAD
     * Test case for deletePet
     *
     * Deletes a pet
     *
     */
    public function test_deletePet() {
=======
     * Test case for addPet
     *
     * Add a new pet to the store
     *
     */
    public function test_addPet() {
>>>>>>> 43c0c359d3be3bcd7168b43937abd3341cc4207f

    }
    
    /**
     * Test case for findPetsByStatus
     *
     * Finds Pets by status
     *
     */
    public function test_findPetsByStatus() {

    }
    
    /**
     * Test case for findPetsByTags
     *
     * Finds Pets by tags
     *
     */
    public function test_findPetsByTags() {

    }
    
    /**
     * Test case for getPetById
     *
     * Find pet by ID
     *
     */
    public function test_getPetById() {

    }
    
    /**
<<<<<<< HEAD
     * Test case for getPetByIdInObject
     *
     * Fake endpoint to test inline arbitrary object return by 'Find pet by ID'
     *
     */
    public function test_getPetByIdInObject() {
=======
     * Test case for updatePetWithForm
     *
     * Updates a pet in the store with form data
     *
     */
    public function test_updatePetWithForm() {
>>>>>>> 43c0c359d3be3bcd7168b43937abd3341cc4207f

    }
    
    /**
<<<<<<< HEAD
     * Test case for petPetIdtestingByteArraytrueGet
     *
     * Fake endpoint to test byte array return by 'Find pet by ID'
     *
     */
    public function test_petPetIdtestingByteArraytrueGet() {
=======
     * Test case for deletePet
     *
     * Deletes a pet
     *
     */
    public function test_deletePet() {
>>>>>>> 43c0c359d3be3bcd7168b43937abd3341cc4207f

    }
    
    /**
<<<<<<< HEAD
     * Test case for updatePet
     *
     * Update an existing pet
     *
     */
    public function test_updatePet() {
=======
     * Test case for uploadFile
     *
     * uploads an image
     *
     */
    public function test_uploadFile() {
>>>>>>> 43c0c359d3be3bcd7168b43937abd3341cc4207f

    }
    
    /**
<<<<<<< HEAD
     * Test case for updatePetWithForm
     *
     * Updates a pet in the store with form data
     *
     */
    public function test_updatePetWithForm() {
=======
     * Test case for getPetByIdWithByteArray
     *
     * Fake endpoint to test byte array return by 'Find pet by ID'
     *
     */
    public function test_getPetByIdWithByteArray() {
>>>>>>> 43c0c359d3be3bcd7168b43937abd3341cc4207f

    }
    
    /**
<<<<<<< HEAD
     * Test case for uploadFile
     *
     * uploads an image
     *
     */
    public function test_uploadFile() {
=======
     * Test case for addPetUsingByteArray
     *
     * Fake endpoint to test byte array in body parameter for adding a new pet to the store
     *
     */
    public function test_addPetUsingByteArray() {
>>>>>>> 43c0c359d3be3bcd7168b43937abd3341cc4207f

    }
    
}
